### ISSUE TITLE
Error on startup after bot prepares slash commands

### ISSUE THREAD

**Issue by wildflowericecoffee** [discordeno/template#147]
Hey there, after I start the bot I see this warning in the terminal, and it appears that the slash commands are not appearing in my guild. Thanks in advance!
```
[28/7/2021 4:11:37 a. m.] INFO > [READY] Bot is online and ready in 2 guild(s)!
[28/7/2021 4:11:37 a. m.] INFO > Preparing Slash Commands...
Error: [403] The Authorization token you passed did not have permission to the resource.
    at Object.processQueue (https://deno.land/x/discordeno@11.2.0/src/rest/process_queue.ts:101:40)
    at async Object.processRequest (https://deno.land/x/discordeno@11.2.0/src/rest/process_request.ts:31:5)
[28/7/2021 4:11:37 a. m.] WARN > Error: Location:
    at Object.runMethod (https://deno.land/x/discordeno@11.2.0/src/rest/run_method.ts:36:9)
    at upsertSlashCommands (https://deno.land/x/discordeno@11.2.0/src/helpers/interactions/commands/upsert_slash_commands.ts:16:21)
    at file:///C:/Users/gm_10/OneDrive/Documents/discordbot/src/events/ready.ts#7:63:13
    at Map.map (https://deno.land/x/discordeno@11.2.0/src/util/collection.ts:95:20)
    at Object.bot.eventHandlers.ready (file:///C:/Users/gm_10/OneDrive/Documents/discordbot/src/events/ready.ts#7:62:18)
[28/7/2021 4:11:37 a. m.] INFO > Updated Guild 😤🙏 (859883782470238268) Slash Commands...
Error: [403] The Authorization token you passed did not have permission to the resource.
    at Object.processQueue (https://deno.land/x/discordeno@11.2.0/src/rest/process_queue.ts:101:40)
    at async Object.processRequest (https://deno.land/x/discordeno@11.2.0/src/rest/process_request.ts:31:5)
[28/7/2021 4:11:37 a. m.] WARN > Error: Location:
    at Object.runMethod (https://deno.land/x/discordeno@11.2.0/src/rest/run_method.ts:36:9)
    at upsertSlashCommands (https://deno.land/x/discordeno@11.2.0/src/helpers/interactions/commands/upsert_slash_commands.ts:16:21)
    at file:///C:/Users/gm_10/OneDrive/Documents/discordbot/src/events/ready.ts#7:63:13
    at Map.map (https://deno.land/x/discordeno@11.2.0/src/util/collection.ts:95:20)
    at Object.bot.eventHandlers.ready (file:///C:/Users/gm_10/OneDrive/Documents/discordbot/src/events/ready.ts#7:62:18)
[28/7/2021 4:11:37 a. m.] INFO > Updated Guild test (814768016298213387) Slash Commands...
[28/7/2021 4:11:37 a. m.] INFO > [READY] Slash Commands loaded successfully!
```

**Comment by Yaikava** [comment]
The bot needs to be invited with the right scopes in order to be able to create slash commands. (`application.commands`)

**Comment by Yaikava** [comment]
This one
![image](https://user-images.githubusercontent.com/83710104/127296893-01bf71d6-e830-4ff7-9910-c9ea00973878.png)

**Comment by wildflowericecoffee** [comment]
Ah, I missed that when creating the invite link. Thank you!
