### ISSUE TITLE
error: Uncaught (in promise) TypeError: Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by chakraecho** [discordeno/template#149]
```javascript
error: Uncaught (in promise) TypeError: Cannot read property 'entries' of undefined

for (const [id, guild] of cached.guilds.entries()) {

^

at Object.createDiscordenoMember (https://raw.githubusercontent.com/discordeno/discordeno/main/src/structures/member.ts:176:47)

at async https://raw.githubusercontent.com/discordeno/discordeno/main/src/handlers/messages/MESSAGE_CREATE.ts:30:36

at async Promise.all (index 0)

at async Object.handleMessageCreate [as MESSAGE_CREATE] (https://raw.githubusercontent.com/discordeno/discordeno/main/src/handlers/messages/MESSAGE_CREATE.ts:26:5)
```

When the bot is trying to reply a message, it goes through create message and try to create a discordenomember. However it seems that the cache does not contain any guilds key.

It seems that this issue only happen in a docker. It is not being triggered when running on windows.

Im using denoland/deno:latest docker. Here's my docker file :   

```DockerFile
# Start from a base image which includes Deno (https://github.com/hayd/deno-docker)
FROM denoland/deno:ubuntu

# Create and move into /bot directory
WORKDIR /bot

# Create a volume to store the database
VOLUME /bot/db

# Copy the source code
COPY . .

RUN chown -R deno:deno /bot
RUN chmod 755 /bot
USER deno

# Cache all of the dependencies so they don't need to be downloaded every run
RUN deno cache deps.ts && \
    deno cache mod.ts

# Finally run the bot
CMD ["run", "-A", "./mod.ts"]
```

**Comment by Yaikava** [comment]
I dont know much about this issue, but try using deno.land instead of github.
(`export * from "https://deno.land/x/discordeno@12.0.1/mod.ts";`)

**Comment by chakraecho** [comment]
solved by changing the deps file. Importing the v12 of discordeno instead of the discordeno main branch
